// Archivo: javascript/desafio.js (Versión con 100 preguntas)

document.addEventListener('DOMContentLoaded', () => {
    // --- Referencias al DOM ---
    const startScreen = document.getElementById('start-screen'), quizScreen = document.getElementById('quiz-screen'), resultsScreen = document.getElementById('results-screen');
    const nicknameInput = document.getElementById('nickname-input'), startButton = document.getElementById('start-button');
    const progressText = document.getElementById('progress-text'), timerEl = document.getElementById('timer');
    const questionText = document.getElementById('question-text'), optionsContainer = document.getElementById('options-container');
    const resultsNickname = document.getElementById('results-nickname'), resultsCorrect = document.getElementById('results-correct'), resultsTime = document.getElementById('results-time');
    const finalScoreEl = document.getElementById('final-score'), leaderboardBody = document.querySelector('#leaderboard-table tbody');

    let currentQuizQuestions = [], currentQuestionIndex = 0, score = 0, timer, secondsElapsed = 0, nickname = '';

    // --- BASE DE DATOS DE 100 PREGUNTAS ---
    const allQuestions = [
        // NIVEL FÁCIL
        { question: "¿Cuál es la altura oficial de la red en la categoría masculina?", options: ["2,35 metros", "2,40 metros", "2,43 metros", "2,50 metros"], correct: 2 },
        { question: "¿Cuántos toques puede dar un equipo antes de pasar el balón al campo contrario (sin contar el bloqueo)?", options: ["2 toques", "3 toques", "4 toques", "Ilimitados"], correct: 1 },
        { question: "¿Cómo se llama el jugador especialista en defensa que viste una camiseta de color diferente?", options: ["Capitán", "Opuesto", "Líbero", "Central"], correct: 2 },
        { question: "¿Cuántos jugadores hay en el campo por equipo?", options: ["5 jugadores", "6 jugadores", "7 jugadores", "11 jugadores"], correct: 1 },
        { question: "¿Con cuántos puntos se gana un set (excepto el set decisivo)?", options: ["15 puntos", "21 puntos", "25 puntos", "30 puntos"], correct: 2 },
        { question: "¿Cuál es la medida de la cancha de voleibol?", options: ["18m x 9m", "20m x 10m", "15m x 7.5m", "28m x 15m"], correct: 0 },
        { question: "¿Qué acción inicia el punto en voleibol?", options: ["El remate", "El bloqueo", "El saque", "La recepción"], correct: 2 },
        { question: "¿Se puede tocar la red durante el juego?", options: ["Sí, siempre", "No, nunca", "Solo si no se interfiere con la jugada", "Solo los delanteros"], correct: 2 },
        { question: "¿Qué es una 'invasión' en voleibol?", options: ["Pasar la mano por encima de la red para rematar", "Pisar completamente el campo contrario por debajo de la red", "Celebrar un punto en campo contrario", "Sacar desde dentro de la cancha"], correct: 1 },
        { question: "¿Cómo se realiza la rotación de los jugadores?", options: ["En sentido contrario a las agujas del reloj", "En el sentido de las agujas del reloj", "Los jugadores no rotan", "Solo rotan los jugadores de atrás"], correct: 1 },
        { question: "¿Qué es un 'toque de dedos' o 'voleo'?", options: ["Un golpe de antebrazos", "Un golpe con la yema de los dedos para colocar el balón", "Un remate suave", "Un tipo de saque"], correct: 1 },
        { question: "¿A cuántos puntos se juega el set decisivo (tie-break)?", options: ["25 puntos", "21 puntos", "15 puntos", "10 puntos"], correct: 2 },
        { question: "¿Puede un jugador tocar el balón dos veces seguidas?", options: ["Sí, siempre", "No, nunca", "Solo si el primer toque fue un bloqueo", "Solo en la recepción del saque"], correct: 2 },
        { question: "¿Cuál es la altura de la red en la categoría femenina?", options: ["2,20 metros", "2,24 metros", "2,30 metros", "2,43 metros"], correct: 1 },
        { question: "¿Qué significa que el balón está 'dentro'?", options: ["Que toca el campo de juego, incluyendo las líneas", "Que toca solo dentro de las líneas", "Que toca el poste de la red", "Que pasa por encima de la antena"], correct: 0 },
        { question: "¿Qué es un 'bloqueo'?", options: ["La acción de los jugadores cerca de la red para interceptar el balón del adversario", "Un tipo de saque", "El tercer toque de un equipo", "Un pase largo"], correct: 0 },
        { question: "¿Qué parte del cuerpo se puede utilizar para golpear el balón?", options: ["Solo las manos y brazos", "Solo la cabeza y el torso", "Cualquier parte del cuerpo", "Solo los pies y las piernas"], correct: 2 },
        { question: "¿Qué es una 'falta de posición'?", options: ["Cuando un jugador no está en su posición correcta en el momento del saque", "Cuando un jugador salta desde la zona de zagueros", "Cuando un jugador toca la red", "Cuando se realizan cuatro toques"], correct: 0 },
        { question: "¿Qué es un 'ataque' o 'remate'?", options: ["El primer toque del equipo", "Toda acción de dirigir el balón hacia el adversario, excepto el saque y el bloqueo", "Un pase al colocador", "Un golpe suave por encima del bloqueo"], correct: 1 },
        { question: "¿Para qué sirven las antenas o varillas?", options: ["Para sostener la red", "Para delimitar el espacio de paso del balón sobre la red", "Para que los jugadores no se golpeen", "Son decorativas"], correct: 1 },
        { question: "¿Qué es un 'saque flotante'?", options: ["Un saque con mucha potencia y giro", "Un saque que no gira y tiene una trayectoria impredecible", "Un saque que se realiza saltando", "Un saque que se realiza por debajo del hombro"], correct: 1 },
        { question: "¿Cuántos sets debe ganar un equipo para ganar el partido?", options: ["2 sets", "3 sets", "4 sets", "5 sets"], correct: 1 },
        { question: "¿Cuál es el objetivo principal del calentamiento antes de un partido?", options: ["Aumentar la temperatura corporal y preparar los músculos para el esfuerzo", "Socializar con los compañeros de equipo", "Estudiar al equipo contrario", "Practicar nuevas jugadas"], correct: 0 },
        { question: "¿Qué cualidad psicológica es fundamental para un buen rendimiento deportivo?", options: ["La agresividad", "La confianza en uno mismo", "La timidez", "La indiferencia"], correct: 1 },
        { question: "¿Qué es el 'juego limpio' o 'fair play'?", options: ["Jugar siempre para ganar", "Respetar las reglas, a los oponentes y a los árbitros", "Protestar todas las decisiones arbitrales", "Distraer al oponente"], correct: 1 },
        // NIVEL MEDIO
        { question: "¿Puede el líbero realizar un saque?", options: ["Sí, si está en la posición 1", "No, nunca", "Solo en el set decisivo", "Solo si el capitán lo autoriza"], correct: 1 },
        { question: "¿Qué sucede si dos jugadores adversarios tocan el balón simultáneamente sobre la red y el balón queda 'retenido'?", options: ["Punto para el equipo que atacaba", "Punto para el equipo que bloqueaba", "Se repite la jugada (doble falta)", "Falta del jugador que tocó el balón en segundo lugar"], correct: 2 },
        { question: "¿Cuántas sustituciones puede realizar un equipo por set?", options: ["4 sustituciones", "6 sustituciones", "8 sustituciones", "Ilimitadas"], correct: 1 },
        { question: "¿Qué es una 'pantalla' en el saque?", options: ["Cuando el sacador tarda más de 8 segundos en sacar", "Cuando un jugador o grupo de jugadores del equipo que saca impide al adversario ver al sacador o la trayectoria del balón", "Cuando el balón toca la red en el saque", "Cuando el saque va dirigido a un jugador específico"], correct: 1 },
        { question: "¿Puede un jugador zaguero completar un golpe de ataque desde la zona de frente?", options: ["Sí, siempre", "No, nunca", "Sí, si al momento del contacto el balón no está completamente por encima del borde superior de la red", "Solo si salta con un pie"], correct: 2 },
        { question: "Si un balón toca la antena después del tercer toque del equipo, ¿qué se sanciona?", options: ["Se repite la jugada", "Balón 'fuera', punto para el equipo contrario", "Se sigue jugando", "Amonestación para el jugador que tocó el balón"], correct: 1 },
        { question: "¿Qué es el Complejo 1 o K-1 en táctica de voleibol?", options: ["La secuencia de juego que comienza con el saque del propio equipo", "La secuencia de juego que comienza con la recepción del saque", "La defensa de un remate", "Una jugada de contraataque"], correct: 1 },
        { question: "¿Qué es una 'sustitución excepcional'?", options: ["Una sustitución que se realiza fuera de la zona de sustitución", "Una sustitución que se realiza cuando un jugador se lesiona y no puede ser reemplazado legalmente", "Cuando un entrenador decide cambiar a todo el equipo", "Una sustitución que no se anota en la planilla"], correct: 1 },
        { question: "En un set, si un jugador titular es sustituido, ¿puede volver a ingresar al juego?", options: ["No, ya no puede volver a ingresar en ese set", "Sí, pero solo una vez y en su posición original", "Sí, puede entrar y salir cuantas veces quiera", "Solo si es para realizar un saque"], correct: 1 },
        { question: "¿Qué es el 'área de calentamiento'?", options: ["El área donde los jugadores realizan el calentamiento antes del partido", "Un área designada donde los jugadores suplentes pueden calentar durante el partido", "El banco de suplentes", "La zona de saque"], correct: 1 },
        { question: "¿Qué es la comunicación asertiva en un equipo?", options: ["Dar órdenes a los compañeros de equipo", "Expresar opiniones y sentimientos de forma clara y respetuosa", "No hablar durante el juego para no distraer", "Criticar a los compañeros cuando cometen errores"], correct: 1 },
        { question: "¿Puede un líbero ser el capitán del equipo?", options: ["Sí, sin restricciones", "No, está prohibido", "Puede ser el capitán del equipo, pero no el capitán en juego", "Solo en la categoría femenina"], correct: 2 },
        { question: "¿Qué es un 'toque asistido'?", options: ["Cuando un jugador ayuda a un compañero a levantarse", "Cuando un jugador se apoya en un compañero o en una estructura para alcanzar el balón", "Cuando dos jugadores golpean el balón al mismo tiempo", "Cuando el entrenador da una indicación al jugador"], correct: 1 },
        { question: "¿Qué ocurre si un equipo se niega a jugar después de haber sido convocado?", options: ["Se le da un tiempo extra para prepararse", "Es declarado ausente y pierde el partido", "Se reanuda el partido desde el punto en que se detuvo", "Se le aplica una sanción económica"], correct: 1 },
        { question: "¿Cómo se define la 'conducta grosera' en el reglamento?", options: ["Celebrar un punto de forma efusiva", "Acción contraria a las buenas costumbres o principios morales", "Discutir con el árbitro", "Realizar un saque muy potente"], correct: 1 },
        { question: "¿Cuál es el peso oficial de un balón de voleibol?", options: ["200-220 gramos", "230-250 gramos", "260-280 gramos", "290-310 gramos"], correct: 2 },
        { question: "¿Qué es el 'espacio de paso' del balón sobre la red?", options: ["El espacio entre la red y el suelo", "El espacio delimitado por el borde superior de la red y las antenas", "Cualquier espacio por encima de la red", "El espacio por debajo de la red"], correct: 1 },
        { question: "¿Cuál es la función principal de un 'opuesto' en un sistema de ataque 5-1?", options: ["Es el colocador principal", "Es el principal atacante, especialmente desde la zona de zagueros", "Es el mejor receptor del equipo", "Es el jugador que menos ataca"], correct: 1 },
        { question: "¿Qué es una 'volcada' (tipping)?", options: ["Un golpe de antebrazos", "Un remate suave con la yema de los dedos para sorprender al bloqueo", "Un tipo de saque", "Una caída defensiva"], correct: 1 },
        { question: "¿Cuál es la función de la línea de ataque?", options: ["Delimita la zona de saque", "Delimita la zona de frente, restringiendo el ataque de los zagueros", "Indica hasta dónde pueden llegar los jugadores al celebrar", "No tiene ninguna función específica"], correct: 1 },
        { question: "¿Qué es un 'tiempo técnico'?", options: ["Un tiempo de descanso solicitado por el entrenador", "Una interrupción automática en los sets del 1 al 4 cuando un equipo alcanza los 8 y 16 puntos", "Un tiempo para que los jugadores se hidraten", "Una interrupción para revisar una jugada en video"], correct: 1 },
        { question: "¿Qué es el 'arousal' en psicología deportiva?", options: ["El nivel de activación fisiológica y psicológica de un deportista", "La capacidad de concentrarse", "La motivación para competir", "La confianza en las propias habilidades"], correct: 0 },
        { question: "¿Qué es un 'anclaje' en el entrenamiento mental?", options: ["Un ejercicio de fuerza", "Un ritual de calentamiento", "Un estímulo (gesto, palabra, imagen) que evoca un estado emocional deseado", "Un objetivo a largo plazo"], correct: 2 },
        { question: "¿Qué es una 'doble falta'?", options: ["Cuando un jugador comete dos faltas seguidas", "Cuando dos jugadores adversarios cometen una falta simultáneamente", "Cuando un equipo realiza cuatro toques", "Cuando el balón toca la red en el saque"], correct: 1 },
        { question: "¿Cuál es la diferencia entre un remate y un bloqueo?", options: ["No hay diferencia", "El remate es una acción ofensiva y el bloqueo es una acción defensiva", "El remate se realiza saltando y el bloqueo no", "El remate se realiza con una mano y el bloqueo con dos"], correct: 1 },
        // NIVEL DIFÍCIL
        { question: "Si un líbero realiza un pase de dedos con manos altas dentro de la zona de frente, ¿puede un compañero rematar el balón por encima del borde superior de la red?", options: ["Sí, sin restricciones", "No, es una falta de ataque", "Solo si el rematador es un jugador zaguero", "Solo si el balón no es devuelto al campo contrario"], correct: 1 },
        { question: "¿En qué consiste el sistema de ataque 6-2?", options: ["6 rematadores y 2 colocadores, donde el colocador zaguero penetra para armar, manteniendo 3 atacantes delanteros", "6 rematadores y 2 colocadores, donde siempre hay un colocador en la red", "6 rematadores y 2 líberos", "Un sistema con 6 jugadores altos y 2 bajos"], correct: 0 },
        { question: "¿Qué es un 'bloqueo completado'?", options: ["Cuando la acción de bloquear es intentada", "Cuando el balón es tocado por un bloqueador", "Cuando el bloqueo resulta en un punto directo", "Cuando participan tres jugadores en el bloqueo"], correct: 1 },
        { question: "Un jugador remata, el balón toca el bloqueo y sale fuera del campo del lado del bloqueador. ¿De quién es el punto?", options: ["Del equipo que atacó", "Del equipo que bloqueó", "Se repite la jugada", "Falta del atacante"], correct: 0 },
        { question: "¿Qué es el Complejo 2 o K-2?", options: ["La secuencia que comienza con la recepción del saque", "La secuencia que comienza con la defensa de un ataque y termina en el contraataque", "Una jugada de segundo toque", "Una jugada con la participación del líbero"], correct: 1 },
        { question: "¿Qué sucede si un jugador es expulsado de un set?", options: ["El equipo juega con un jugador menos", "Debe ser sustituido legalmente o de forma excepcional, y no puede volver a jugar en ese set", "Puede volver a ingresar después de 5 puntos", "Es expulsado del partido"], correct: 1 },
        { question: "¿Puede un balón que sale por fuera de la antena ser recuperado?", options: ["Sí, siempre", "No, nunca", "Solo si es el primer toque del equipo y el balón vuelve por el mismo lado exterior", "Solo si es recuperado por el líbero"], correct: 2 },
        { question: "¿Cuál es la función del segundo árbitro?", options: ["Controlar el marcador", "Asistir al primer árbitro, controlar las bancas, las sustituciones y las faltas de red y de línea central", "Autorizar el saque", "Llevar el tiempo de juego"], correct: 1 },
        { question: "¿Qué es el 'estado de flow' o 'estar en la zona'?", options: ["Un estado de cansancio extremo", "Un estado de máxima concentración y rendimiento en el que la acción fluye sin esfuerzo", "Un estado de nerviosismo antes de la competencia", "La celebración de un punto"], correct: 1 },
        { question: "En un sistema de recepción con 3 jugadores en forma de 'W', ¿quiénes son los receptores principales?", options: ["Los tres jugadores delanteros", "Los tres jugadores zagueros", "Los dos jugadores de las puntas y el central zaguero", "Depende de la rotación"], correct: 2 },
        { question: "¿Qué significa que una conducta incorrecta sea sancionada con 'castigo'?", options: ["Una advertencia verbal", "La expulsión del set", "Un punto y el saque para el adversario", "La descalificación del partido"], correct: 2 },
        { question: "¿A qué se refiere el término 'tándem' en una combinación de ataque?", options: ["Un ataque rápido por el centro", "Cuando un jugador ataca un segundo tiempo justo detrás de un jugador que amaga un primer tiempo", "Un ataque desde la zona de zagueros", "Un cruce de los atacantes"], correct: 1 },
        { question: "¿Cuál es el procedimiento si el balón rompe la malla de la red durante una jugada?", options: ["Punto para el equipo que lanzó el balón", "Punto para el equipo que defendía", "Se anula la jugada y se repite", "El juego continúa"], correct: 2 },
        { question: "Si un equipo realiza una solicitud de sustitución improcedente por primera vez en el partido, ¿cuál es la consecuencia?", options: ["Castigo: punto y saque para el adversario", "Amonestación por demora", "La solicitud es rechazada sin sanción, pero se registra en la planilla", "Expulsión del entrenador"], correct: 2 },
        { question: "¿Qué es la 'penetración' de un colocador zaguero?", options: ["El movimiento del colocador desde la zona de zagueros hacia la red para armar el ataque", "Cuando el colocador pisa la línea de ataque", "Cuando el colocador remata desde la zona de zagueros", "Cuando el colocador realiza un bloqueo"], correct: 0 },
        { question: "En una recepción de 4 jugadores en rombo, ¿cuál es la función del jugador más adelantado?", options: ["Recibir los saques largos", "Recibir los saques cortos", "No participa en la recepción", "Realizar el primer ataque"], correct: 1 },
        { question: "¿Qué es la 'visualización' en el entrenamiento mental?", options: ["Ver videos de partidos anteriores", "Imaginar mentalmente la ejecución exitosa de una habilidad o situación de juego", "Observar a los compañeros de equipo", "Analizar las estadísticas del rival"], correct: 1 },
        { question: "¿En qué consiste el 'principio de sobrecarga' en el entrenamiento físico?", options: ["Realizar siempre los mismos ejercicios", "Entrenar con una intensidad o carga superior a la que el cuerpo está acostumbrado para generar adaptaciones", "Descansar más tiempo del que se entrena", "Entrenar solo una vez por semana"], correct: 1 },
        { question: "¿Cuál es la señal manual del árbitro para 'cuatro toques'?", options: ["Levantar cuatro dedos, desplegados", "Hacer un círculo con el dedo índice", "Levantar dos dedos", "Mostrar la tarjeta roja"], correct: 0 },
        { question: "¿Puede un jugador tocar el balón en el espacio adversario antes del golpe de ataque del oponente?", options: ["Sí, si no interfiere", "No, es una falta", "Solo durante el bloqueo", "Solo si es el líbero"], correct: 2 },
        { question: "¿Qué es la 'cohesión de equipo'?", options: ["El grado en que los miembros de un equipo se sienten unidos y trabajan juntos hacia un objetivo común", "La capacidad física del equipo", "El sistema táctico del equipo", "El número de jugadores en el equipo"], correct: 0 },
        { question: "Si un jugador expulsado no puede ser sustituido legal o excepcionalmente, ¿qué sucede?", options: ["El jugador puede continuar en el campo", "El equipo es declarado incompleto y pierde el set", "El equipo juega con un jugador menos", "Se le permite al entrenador entrar en su lugar"], correct: 1 },
        { question: "¿Cuál es el tiempo máximo que tiene un sacador para ejecutar el saque después del silbato del árbitro?", options: ["5 segundos", "8 segundos", "10 segundos", "No hay límite de tiempo"], correct: 1 },
        { question: "¿A qué se refiere el 'clima motivacional orientado a la tarea'?", options: ["Un entorno donde se reconoce solo a los mejores jugadores", "Un entorno donde se anima y recompensa el esfuerzo y la mejora personal", "Un entorno donde se castigan los errores", "Un entorno donde no hay competencia"], correct: 1 },
        { question: "¿Qué es un 'pase tendido' o 'alma' en la nomenclatura de ataque?", options: ["Un pase alto a la punta", "Un pase rápido y de trayectoria baja a una posición intermedia entre el centro y la punta", "Un pase hacia atrás", "Un pase para un ataque zaguero"], correct: 1 },
        // NIVEL EXPERTO
        { question: "Si el balón golpea a un árbitro durante el juego, ¿cuál es la decisión correcta?", options: ["Punto para el equipo que no tocó al árbitro", "Se repite la jugada", "Se considera 'balón fuera', punto para el equipo contrario", "El juego continúa"], correct: 2 },
        { question: "¿En qué consiste el 'bloqueo de lectura'?", options: ["El bloqueador salta antes de que el colocador arme", "El bloqueador lee la trayectoria del pase y reacciona para desplazarse y saltar", "El bloqueador siempre salta con el atacante central", "El bloqueador intenta adivinar a dónde irá el ataque"], correct: 1 },
        { question: "Un jugador remata, el balón es defendido por el equipo contrario y, en la misma jugada, vuelve a su campo. ¿Puede ese mismo jugador realizar el siguiente toque?", options: ["No, sería doble toque", "Sí, sin problemas, es un nuevo inicio de jugada para su equipo", "Solo si es el segundo toque del equipo", "Solo si es un jugador zaguero"], correct: 1 },
        { question: "¿Cuál es la principal diferencia entre una 'sustitución excepcional' y una 're-designación de líbero'?", options: ["No hay diferencia", "La sustitución excepcional es para cualquier jugador lesionado, la re-designación es específica para un líbero que no puede continuar", "La sustitución excepcional cuenta en el total de 6, la re-designación no", "La re-designación solo se puede hacer una vez por partido"], correct: 1 },
        { question: "¿Qué es la 'periodización' en el entrenamiento deportivo?", options: ["El calentamiento antes de un partido", "La planificación del entrenamiento en ciclos para alcanzar el máximo rendimiento en momentos clave", "La vuelta a la calma después de entrenar", "Un tipo de ejercicio de fuerza"], correct: 1 },
        { question: "¿Qué es la 'ansiedad rasgo' en un deportista?", options: ["La ansiedad que se siente justo antes de una competencia", "Una disposición de la personalidad a percibir ciertas situaciones como amenazantes", "El miedo a lesionarse", "La presión de los espectadores"], correct: 1 },
        { question: "En una combinación de ataque llamada 'doble batida', ¿qué hace el atacante?", options: ["Salta dos veces para rematar", "Finge un ataque de primer tiempo y luego se desplaza para atacar un segundo tiempo", "Ataca con las dos manos", "Realiza dos ataques en la misma jugada"], correct: 1 },
        { question: "¿Cuál es la sanción por una segunda 'demora de juego' por parte del mismo equipo en un partido?", options: ["Amonestación verbal", "Tarjeta amarilla", "Castigo por demora: un punto y el saque para el adversario", "Expulsión del capitán"], correct: 2 },
        { question: "¿Cuál es la función del 'capitán en juego'?", options: ["Asumir las responsabilidades del capitán del equipo cuando este no está en la cancha", "Dirigir el calentamiento", "Llevar las estadísticas del equipo", "Decidir las sustituciones"], correct: 0 },
        { question: "¿Qué es el 'modelo multidimensional de liderazgo' de Chelladurai?", options: ["Un modelo que describe diferentes estilos de comunicación", "Un modelo que explica cómo la eficacia del liderazgo depende de la congruencia entre la conducta requerida, la preferida y la real del líder", "Una teoría sobre la motivación en el deporte", "Un método para la resolución de conflictos en el equipo"], correct: 1 },
        { question: "¿Puede el segundo árbitro pitar una falta que no está en su rango de jurisdicción?", options: ["No, nunca", "Sí, pero sin insistir al primer árbitro", "Sí, y su decisión es final", "Solo si el primer árbitro no está mirando"], correct: 1 },
        { question: "En el sistema digital norteamericano (SDN) para nombrar los ataques, ¿qué significa una jugada '51'?", options: ["Un pase alto a la posición 5", "Un ataque de segundo tiempo por el centro", "Un ataque de primer tiempo (corta) por delante del colocador", "Un ataque desde zaguero por posición 1"], correct: 2 },
        { question: "¿Qué es la 'reestructuración cognitiva' como técnica de intervención psicológica?", options: ["Un método de relajación", "Una técnica para mejorar la concentración", "Una estrategia para identificar y cambiar pensamientos negativos o irracionales por otros más positivos y adaptativos", "Una técnica de visualización"], correct: 2 },
        { question: "Si un balón toca la parte superior del poste de la red por fuera de las antenas, ¿se considera 'fuera'?", options: ["No, el juego continúa", "Sí, es falta", "Depende de si fue en el primer, segundo o tercer toque", "Solo si interfiere con la jugada"], correct: 1 },
        { question: "¿En qué consiste el principio de 'individualización' en el entrenamiento?", options: ["Entrenar a todos los jugadores de la misma manera", "Adaptar el entrenamiento a las características y necesidades específicas de cada jugador", "Fomentar la competencia individual por encima del equipo", "Realizar solo entrenamientos individuales"], correct: 1 },
        { question: "Un jugador salta desde la zona de zagueros para atacar. Al momento del golpe, el balón está completamente por encima del borde superior de la red, pero el jugador cae dentro de la zona de frente. ¿Es una acción legal?", options: ["Sí, si no tocó la red", "No, es una falta de ataque de zaguero", "Sí, porque el despegue fue detrás de la línea de ataque", "Solo si es el opuesto"], correct: 2 },
        { question: "¿Cuál es la diferencia entre 'conducta ofensiva' y 'agresión' según el reglamento?", options: ["No hay diferencia", "La conducta ofensiva se refiere a gestos o palabras difamatorias, mientras que la agresión es un ataque físico o amenaza", "La conducta ofensiva es una falta menor y la agresión es una falta grave", "La agresión solo se sanciona si hay contacto físico"], correct: 1 },
        { question: "¿Puede un equipo solicitar un tiempo de descanso después de haber tenido una solicitud de sustitución rechazada por demora en la misma interrupción?", options: ["Sí, sin problema", "No, no está permitido", "Solo si lo solicita el capitán", "Solo si quedan tiempos de descanso disponibles"], correct: 1 },
        { question: "¿Cuál es el rol del 'árbitro de desafío' (Challenge Referee) en las competencias de la FIVB?", options: ["Es el segundo árbitro", "Es un juez de línea", "Supervisa el proceso del sistema de video desafío (Video Challenge System)", "Es el árbitro de reserva"], correct: 2 },
        { question: "En un sistema defensivo '2-1-3', ¿quién es el jugador que se adelanta para cubrir las fintas cortas?", options: ["El colocador", "El central delantero que no participa en el bloqueo, o un zaguero", "El líbero", "El opuesto"], correct: 1 },
        { question: "¿Qué es la 'disquinesia escapular' y por qué es relevante en el voleibol?", options: ["Un tipo de lesión en la rodilla", "Una alteración en el movimiento normal del omóplato (escápula), que puede aumentar el riesgo de lesiones en el hombro de los rematadores", "Una técnica de saque", "Un ejercicio de estiramiento"], correct: 1 },
        { question: "Si un jugador expulsado o descalificado no puede ser sustituido legal o excepcionalmente, ¿qué sucede?", options: ["El equipo juega con un jugador menos durante 3 puntos", "El equipo es declarado incompleto", "El entrenador puede entrar a jugar", "Se le permite al jugador reingresar"], correct: 1 },
        { question: "¿Cuál es la función del 'árbitro de reserva' en las competencias de la FIVB?", options: ["Reemplazar al segundo árbitro si es necesario y ayudar en diversas tareas de control", "Ser el anotador principal", "Ser un juez de línea adicional", "Controlar el tiempo de los intervalos"], correct: 0 },
        { question: "¿En qué consiste la comunicación no verbal, qué porcentaje del tiempo se recomienda establecer contacto visual al hablar y al escuchar para ser asertivo?", options: ["100% al hablar, 0% al escuchar", "40% al hablar, 75% al escuchar", "75% al hablar, 40% al escuchar", "50% al hablar, 50% al escuchar"], correct: 1 },
        { question: "Según el 'Modelo de rendimiento de equipo de 7 fases' de Drexler/Sibbet, ¿cuál es la fase que sigue a la 'Aclaración de objetivos / roles'?", options: ["Implementación", "Creación de confianza", "Compromiso, Toma de decisiones", "Alto rendimiento"], correct: 2 }
    ];

    // --- Lógica del Juego ---
    startButton.addEventListener('click', () => { nickname = nicknameInput.value.trim(); if (nickname.length >= 3 && nickname.length <= 12) { startGame(); } else { alert('Por favor, introduce un apodo de 3 a 12 caracteres.'); } });
    function startGame() { currentQuestionIndex = 0; score = 0; secondsElapsed = 0; currentQuizQuestions = [...allQuestions].sort(() => 0.5 - Math.random()).slice(0, 20); startScreen.style.display = 'none'; resultsScreen.style.display = 'none'; quizScreen.style.display = 'block'; startTimer(); showNextQuestion(); }
    function startTimer() { timerEl.textContent = '00:00'; timer = setInterval(() => { secondsElapsed++; const minutes = Math.floor(secondsElapsed / 60).toString().padStart(2, '0'); const seconds = (secondsElapsed % 60).toString().padStart(2, '0'); timerEl.textContent = `${minutes}:${seconds}`; }, 1000); }
    function showNextQuestion() { if (currentQuestionIndex >= currentQuizQuestions.length) { endGame(); return; } const question = currentQuizQuestions[currentQuestionIndex]; progressText.textContent = `Pregunta ${currentQuestionIndex + 1} / 20`; questionText.textContent = question.question; optionsContainer.innerHTML = ''; question.options.forEach((option, index) => { const button = document.createElement('button'); button.className = 'option-btn'; button.textContent = option; button.dataset.index = index; button.addEventListener('click', handleAnswer); optionsContainer.appendChild(button); }); }
    function handleAnswer(event) { const selectedButton = event.target; const selectedIndex = parseInt(selectedButton.dataset.index); const correctIndex = currentQuizQuestions[currentQuestionIndex].correct; document.querySelectorAll('.option-btn').forEach(btn => btn.disabled = true); if (selectedIndex === correctIndex) { score++; selectedButton.classList.add('correct'); } else { selectedButton.classList.add('incorrect'); document.querySelector(`.option-btn[data-index="${correctIndex}"]`).classList.add('correct'); } currentQuestionIndex++; setTimeout(showNextQuestion, 1200); }
    function endGame() { clearInterval(timer); quizScreen.style.display = 'none'; resultsScreen.style.display = 'block'; const finalScore = (score * 1000) - secondsElapsed; resultsNickname.textContent = `¡Felicidades, ${nickname}!`; resultsCorrect.textContent = `${score} / 20`; resultsTime.textContent = timerEl.textContent; finalScoreEl.textContent = `${finalScore} Puntos`; displayLeaderboard(nickname, finalScore); }
    function displayLeaderboard(userNickname, userScore) { let leaderboardData = [ { nickname: 'VoleyPro', score: 19850 }, { nickname: 'Spiker', score: 19823 }, { nickname: 'LíberoKing', score: 18790 }, { nickname: 'SetterStar', score: 18754 }, { nickname: 'AceMaker', score: 17690 }, { nickname: 'DigMaster', score: 16650 }, { nickname: 'Rookie', score: 15600 }, { nickname: 'ElCentral', score: 14555 }, { nickname: 'FlyHighFan', score: 13500 }, { nickname: 'PlayerOne', score: 12450 } ]; leaderboardData.push({ nickname: userNickname, score: userScore }); leaderboardData.sort((a, b) => b.score - a.score); leaderboardData = leaderboardData.slice(0, 10); leaderboardBody.innerHTML = ''; leaderboardData.forEach((entry, index) => { const row = document.createElement('tr'); if (entry.nickname === userNickname && entry.score === userScore) { row.className = 'user-score'; } row.innerHTML = `<td>#${index + 1}</td><td>${entry.nickname}</td><td>${entry.score}</td>`; leaderboardBody.appendChild(row); }); }
    document.getElementById('play-again-button').addEventListener('click', () => { resultsScreen.style.display = 'none'; startScreen.style.display = 'block'; nicknameInput.value = ''; });
});